name: Java CI with Maven

# Run on push to `main` or PR targeting `main`
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # Install JDK 11 and cache dependencies
      - name: Set up Java JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      # This targets the parent `pom.xml` file.
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Copy build outputs to staging directory
        run: mkdir staging && cp target/*.jar staging

      - name: List staging directory contents
        run: ls -la staging

      - name: Upload build artifacts to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
